# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Xu Lei
tagline:          'TechNotes'
description:      'TechNotes'
url:              http://lxu.tech
baseurl:          /

author:
  name:           'Mark  Otto'
  url:            https://twitter.com/mdo

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lxuc
